#!/bin/bash

for NAME in herbert louise roy
do
	echo $NAME
	echo ${NAME}InspectResponse >> ${NAME}InspectResponse.txt
	echo ${NAME}TalkResponse >> ${NAME}TalkResponse.txt
	echo ${NAME}interrogateResponse >> ${NAME}InterrogateResponse.txt
	echo ${NAME}accuseResponse >> ${NAME}AccuseResponse.txt
	echo ${NAME}itemResponse1 >> ${NAME}ItemResponse1.txt
	echo ${NAME}itemResponse2 >> ${NAME}ItemResponse2.txt
	echo ${NAME}itemResponse3 >> ${NAME}ItemResponse3.txt
	echo ${NAME}itemResponseGeneric >> ${NAME}ItemResponseGeneric.txt
done
